version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - run:
          name: Install GCC ARM Embedded
          working_directory: /opt
          command: |
              dpkg --add-architecture i386
              apt-get -y update
              apt-get -y install libc6:i386 libncurses5:i386 libstdc++6:i386
              wget -O gcc_arm_embedded.tar.bz2 "https://developer.arm.com/-/media/Files/downloads/gnu-rm/5_3-2016q1/gccarmnoneeabi532016q120160330linuxtar.bz2?revision=417e2623-c259-4a12-aacc-c87200b569c7?product=GNU%20Arm%20Embedded%20Toolchain,32-bit,,Linux,5-2016-q1-update"
              tar -jxf gcc_arm_embedded.tar.bz2
              echo 'export PATH="/opt/gcc-arm-none-eabi-5_3-2016q1/bin:$PATH"' >> $BASH_ENV
      
      - run:
          name: Install and configure mbed-cli
          command: |
              echo Installing mbed
              pip install mbed-cli
              echo Finished installing mbed
              echo Configuring mbed
              mbed config -G ARM_PATH /opt/gcc-arm-none-eabi-5_3-2016q1/bin
              mbed config --list
              mbed toolchain -G GCC_ARM
              mbed target -G UBLOX_EVK_ODIN_W2
      
      - checkout

      - run:
          name: Compile
          command: mbed compile

      - run:
          name: Print the Current Time
          command: date
