/*
 * host_comms_shared.h
 *
 *  Created on: 25-Feb-2023
 *      Author: Samvrit
 */

#ifndef DEVICE_COMMS_HOST_COMMS_SHARED_H_
#define DEVICE_COMMS_HOST_COMMS_SHARED_H_

#define FAST_LOGGING_NUM_SIGNALS (2U)
#define FAST_LOGGING_BUFFER_SIZE (1000U)

enum host_data_E
{
    X_HAT_0,
    X_HAT_1,
    X_HAT_2,
    X_HAT_3,
    X_HAT_4,
    X_HAT_5,

    TORQUE_CMD,

    MEASUREMENTS_0,
    MEASUREMENTS_1,
    MEASUREMENTS_2,

    RLS_ERROR_BITFIELD,
    MOTOR_FAULT_FLAG,

    CONTROLLER_STATE,

    CURRENT_FB,
    V_BRIDGE,
    DUTY_RATIO,

    SLOW_LOGGING_MAX,

    FAST_LOGGING_SIGNALS_READY,
    FAST_LOGGING_SIGNAL1,
    FAST_LOGGING_SIGNAL2,
    FAST_LOGGING_MAX,
    FAST_LOGGING_SIGNALS_DONE,

    DATA_MAX,
};

enum host_commands_E
{
    ZERO_POSITION_OFFSET = 1,
    START_STREAMING_DATA,
    STOP_STREAMING_DATA,
    TRIGGER_FAST_LOGGING,

    DUTY_RATIO_OVERRIDE,
    DIRECTION_TOGGLE,
    TORQUE_CMD_OVERRIDE,
    MOTOR_ENABLE_TOGGLE,
    RESET_MOTOR,
    OVERRIDE_TOGGLE,
};


#endif /* DEVICE_COMMS_HOST_COMMS_SHARED_H_ */
